"""add hostname and os_guess to discovered_hosts

Revision ID: 2cdd44f902a4
Revises: 44ee9312ab7a
Create Date: 2026-09-22 18:31:37.156649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdd44f902a4'
down_revision: Union[str, Sequence[str], None] = '44ee9312ab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_hosts', sa.Column('hostname', sa.String(), nullable=True))
    op.add_column('discovered_hosts', sa.Column('os_guess', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovered_hosts', 'os_guess')
    op.drop_column('discovered_hosts', 'hostname')
    # ### end Alembic commands ###
