"""add network_links table

Revision ID: 8c5484bc7874
Revises: 2cdd44f902a4
Create Date: 2026-09-29 19:13:49.364871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5484bc7874'
down_revision: Union[str, Sequence[str], None] = '2cdd44f902a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('target_ip', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_links_id'), 'network_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_links_id'), table_name='network_links')
    op.drop_table('network_links')
    # ### end Alembic commands ###
