"""add host_ip to containers

Revision ID: a028b82fb265
Revises: 6665f6fbf27a
Create Date: 2026-10-02 18:09:34.924236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028b82fb265'
down_revision: Union[str, Sequence[str], None] = '6665f6fbf27a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('host_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'host_ip')
    # ### end Alembic commands ###
